"""Migrate the Campus Inventory SQLite database to PostgreSQL.

Usage:
    python postgresql.py --database-url postgresql://user:password@localhost:5432/campus_inventory

Environment variables may be used instead:
    DATABASE_URL=postgresql://user:password@localhost:5432/campus_inventory
    SQLITE_PATH=lab_tracker.db
"""

import argparse
import os
import sqlite3
from pathlib import Path

import psycopg


PROJECT_ROOT = Path(__file__).resolve().parent
DEFAULT_SQLITE_PATH = PROJECT_ROOT / "lab_tracker.db"


SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(320) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role VARCHAR(10) NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'user')),
    login_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS inventory (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    availability_status VARCHAR(20) NOT NULL DEFAULT 'Available'
        CHECK (availability_status IN ('Available', 'On Hold')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS borrow_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id INTEGER NOT NULL REFERENCES inventory(id),
    user_id INTEGER NOT NULL REFERENCES users(id),
    student_name VARCHAR(100) NOT NULL,
    student_id VARCHAR(30) NOT NULL,
    section VARCHAR(50) NOT NULL,
    course VARCHAR(100) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL DEFAULT 'Borrowed'
        CHECK (status IN ('Borrowed', 'Missing', 'Returned')),
    borrowed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    returned_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reservations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id INTEGER NOT NULL REFERENCES inventory(id),
    user_id INTEGER NOT NULL REFERENCES users(id),
    student_name VARCHAR(100) NOT NULL,
    student_id VARCHAR(30) NOT NULL,
    section VARCHAR(50) NOT NULL,
    course VARCHAR(100) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    reservation_date VARCHAR(20) NOT NULL,
    reservation_time VARCHAR(10) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Pending'
        CHECK (status IN ('Pending', 'On Hold', 'Approved', 'Rejected')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""


TABLE_COLUMNS = {
    "users": (
        "id", "username", "email", "password_hash", "role", "login_attempts", "locked_until"
    ),
    "inventory": (
        "id", "item_name", "category", "quantity", "unit_price", "availability_status",
        "created_at", "updated_at"
    ),
    "borrow_records": (
        "id", "inventory_id", "user_id", "student_name", "student_id", "section", "course",
        "quantity", "status", "borrowed_at", "returned_at"
    ),
    "reservations": (
        "id", "inventory_id", "user_id", "student_name", "student_id", "section", "course",
        "quantity", "reservation_date", "reservation_time", "status", "created_at"
    ),
}


def read_sqlite_rows(sqlite_path):
    with sqlite3.connect(sqlite_path) as connection:
        connection.row_factory = sqlite3.Row
        return {
            table_name: [dict(row) for row in connection.execute(f"SELECT * FROM {table_name}")]
            for table_name in TABLE_COLUMNS
        }


def migrate(sqlite_path, database_url, reset=False):
    sqlite_path = Path(sqlite_path)
    if not sqlite_path.exists():
        raise FileNotFoundError(f"SQLite database not found: {sqlite_path}")

    rows_by_table = read_sqlite_rows(sqlite_path)
    with psycopg.connect(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute(SCHEMA)
            if reset:
                cursor.execute(
                    "TRUNCATE TABLE borrow_records, reservations, inventory, users "
                    "RESTART IDENTITY CASCADE"
                )
            for table_name, columns in TABLE_COLUMNS.items():
                column_list = ", ".join(columns)
                placeholders = ", ".join(f"%({column})s" for column in columns)
                updates = ", ".join(
                    f"{column} = EXCLUDED.{column}"
                    for column in columns
                    if column != "id"
                )
                query = (
                    f"INSERT INTO {table_name} ({column_list}) VALUES ({placeholders}) "
                    f"ON CONFLICT (id) DO UPDATE SET {updates}"
                )
                for row in rows_by_table[table_name]:
                    cursor.execute(query, row)

            for table_name in TABLE_COLUMNS:
                cursor.execute(
                    f"SELECT setval(pg_get_serial_sequence(%s, 'id'), "
                    f"COALESCE((SELECT MAX(id) FROM {table_name}), 1), true)",
                    (table_name,),
                )

        connection.commit()

    counts = ", ".join(
        f"{table_name}={len(rows)}" for table_name, rows in rows_by_table.items()
    )
    print(f"Migration complete: {counts}")


def main():
    parser = argparse.ArgumentParser(description="Migrate SQLite data to PostgreSQL.")
    parser.add_argument(
        "--sqlite-path",
        default=os.environ.get("SQLITE_PATH", str(DEFAULT_SQLITE_PATH)),
        help="Path to the SQLite database file.",
    )
    parser.add_argument(
        "--database-url",
        default=os.environ.get("DATABASE_URL"),
        help="PostgreSQL connection URL.",
    )
    parser.add_argument(
        "--reset",
        action="store_true",
        help="Delete existing PostgreSQL rows before importing. Use with care.",
    )
    arguments = parser.parse_args()
    if not arguments.database_url:
        parser.error("Provide --database-url or set DATABASE_URL.")
    migrate(arguments.sqlite_path, arguments.database_url, arguments.reset)


if __name__ == "__main__":
    main()
